-- Q1. Total revenue generated by male vs female customers
SELECT 
    gender,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY gender;



-- Q2. Customers who used discount and spent more than average purchase amount
SELECT 
    customer_id,
    purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
  AND purchase_amount >= (
        SELECT AVG(purchase_amount)
        FROM customer
    );



-- Q3. Top 5 products with highest average review rating
SELECT 
    item_purchased AS product,
    ROUND(AVG(review_rating::NUMERIC), 2) AS avg_review_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_review_rating DESC
LIMIT 5;



-- Q4. Compare average purchase amount between Standard and Express shipping
SELECT 
    shipping_type,
    ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;



-- Q5. Do subscribed customers spend more?
SELECT 
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS avg_spend,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY avg_spend DESC, total_revenue DESC;



-- Q6. Top 5 products with highest percentage of discounted purchases
SELECT 
    item_purchased AS product,
    ROUND(
        100.0 * SUM(
            CASE 
                WHEN discount_applied = 'Yes' THEN 1 
                ELSE 0 
            END
        ) / COUNT(*), 
        2
    ) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

SELECT 
    CASE 
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    
    COUNT(*) AS customer_count

FROM customer

GROUP BY customer_segment
ORDER BY customer_count 

--Q8. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q9. What is the revenue contribution of each age group? 

SELECT age_group , SUM(purchase_amount) AS revenue
FROM customer
GROUP BY age_group

